language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install pyqt5
  - pip install pytest-ipynb
  - pip install --quiet .
# command to run tests
script:
  - py.test --no-qt
